# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_source = '''
'''
hook_add = '''
let g:neosnippet#enable_completed_snippet = 1
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = "Shougo/neosnippet.vim"


[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang& helplang=en,ja
'''

# vimsell{{{
[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = '''
nmap <silent> vs :<C-u>VimShellPop<CR>
'''
depends = 'Shougo/vimproc.vim'
# }}}

[[plugins]]
repo = 'itchyny/dictionary.vim'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

