[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'itchyny/vim-cursorword'

# unite {{{
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/Unite.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''

'''

[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'kmnk/vim-unite-giti'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'Shougo/neossh.vim'
# }}}
# filer {{{
[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = '''
let g:vimfiler_as_default_explorer=1
let g:vimfiler_ignore_pattern = ['^\.git$', '^\.DS_Store$']
'''
# }}}
# vimsell{{{
[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = '''
nmap <silent> vs :<C-u>VimShellPop<CR>
'''
depends = 'vimproc'
# }}}
#completion {{{
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''let g:neosnippet#enable_completed_snippet = 1'''
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
# }}}
#comletion sources {{{
[[plugins]]
repo = 'ujihisa/neco-look'
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
[[plugins]]
repo = 'wokalski/autocomplete-flow'
# }}}
#operator {{{
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'
hook_add = '''
map <silent>sa <Plug>(operator-surround-append)
map <silent>sd <Plug>(operator-surround-delete)
map <silent>sr <Plug>(operator-surround-replace)
'''
[[plugins]]
repo = 'osyo-manga/vim-operator-stay-cursor'
[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
map R <Plug>(operator-replace)
'''
# }}}
# textobj {{{ 
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'thinca/vim-textobj-between'
hook_add = '''
omap if <Plug>(textobj-between-i)
omap af <Plug>(textobj-between-a)
vmap if <Plug>(textobj-between-i)
vmap af <Plug>(textobj-between-a)
'''
[[plugins]] # il al
repo = 'kana/vim-textobj-line'
[[plugins]] # iz az
repo = 'kana/vim-textobj-fold'
[[plugins]]
repo = 'gcmt/wildfire.vim'
hook_add='''
let g:wildfire_objects = {
    \ "html,xml" : ["at", "it"],
\ }
'''
# }}}
# execute {{{
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''
[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_enable_realtime  = 1
'''
# }}}
# view {{{
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]] # insert 時に行番号を光らせる
repo = 'cohama/vim-insert-linenr'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=250
'''
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_sign_column_always = 1
'''
# }}}
# syntax {{{
## lang
[[plugins]] # github flaovoed markwon
repo = 'rhysd/vim-gfm-syntax'
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'digitaltoad/vim-jade'
[[plugins]]
repo = 'wavded/vim-stylus'
[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
on_ft = 'php'
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'jsx']
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
'''
[[plugins]] #.pde
repo = 'sophacles/vim-processing'
[[plugins]] 
repo = 'jeroenbourgois/vim-actionscript'
hook_add = '''
'''
[[plugins]] 
repo = 'aklt/plantuml-syntax'
hook_add = '''
'''
[[plugins]] 
repo = 'slim-template/vim-slim'
hook_add = '''
'''
[[plugins]]
# repo = 'othree/yajs.vim'
repo = 'pangloss/vim-javascript'
on_ft = 'js'
[[plugins]] 
repo = 'tikhomirov/vim-glsl'
on_ft = 'glsl'
[[plugins]]
repo = 'ElmCast/elm-vim'
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:elm_syntastic_show_warnings = 1
'''
[[plugins]]
repo = 'ryym/vim-riot'
hook_add = '''
'''

#benri
# [[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
# repo = 'osyo-manga/vim-precious'
# on_i = 1
# depends = ['context_filetype.vim']
# hook_add = '''
# let g:precious_enable_switch_CursorMoved = { '*': 1, 'help':0 }
# INSERTモードのON／OFFに合わせてトグル
# autocmd MyAutoCmd InsertEnter * :PreciousSwitch
# autocmd MyAutoCmd InsertLeave * :PreciousReset
# '''
[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'
# }}}
# input {{{
[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
au Filetype markdown let b:AutoPairs = {'(':')','{':'}',"'":"'",'"':'"', '`':'`'}
'''
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key = '<C-e>'
let g:user_emmet_settings = {
            \'variables':{
            \       'lang' : 'ja'
            \}
            \}
'''
[[plugins]]
repo = 'kana/vim-submode'
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''
[[plugins]]
repo     = 'junegunn/vim-easy-align'
hook_add = 'vmap <Enter> <Plug>(EasyAlign)'
[[plugins]] # true false などをtoggle
repo = 'AndrewRadev/switch.vim'
hook_add = '''
nnoremap - :<C-u>Switch<CR>
'''
[[plugins]]
repo     = 'haya14busa/vim-auto-programming'
hook_add = '''
set completefunc=autoprogramming#complete
'''
# }}}
# search {{{
[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/  <Plug>(incsearch-stay)
'''
# }}}
# speed {{{
[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_source = '''
let g:loaded_matchparen = 1
'''
# }}}
# git {{{
[[plugins]]
repo = 'hotwatermorning/auto-git-diff'
hook_add = '''
let g:auto_git_diff_show_window_at_right=1
'''
#}}}

# markdown {{{
[[plugins]]
repo = 'gabrielelana/vim-markdown'
hook_add='''
let g:markdown_mapping_switch_status='<Space><Space>'
'''
#}}}

# fold
[[plugins]]
repo = 'Konfekt/FastFold'

# not use
[[plugins]] #session
repo = 'tpope/vim-obsession'
[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
[[plugins]]
repo = 'itchyny/dictionary.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
