[[plugins]]
repo = 'Shougo/Unite.vim'
hook_add = '''
call unite#custom#source('file', 'matchers', "matcher_default")
let g:unite_sorce_history_yank_enable =1
call unite#custom#profile('default', 'context', {
\   'start_insert': 1,
\   'prompt_direction': 'top',
\   'split' : 0,
\})
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'kmnk/vim-unite-giti'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'Shougo/neossh.vim'
[[plugins]]
repo = 'Shougo/unite-outline'
